[workspace]
authors = ["Francesco Frassinelli <francesco.frassinelli@nina.no>"]
channels = ["conda-forge"]
name = "coat-shiny"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
"r-data.table" = ">=1.17.8,<2"
r-httr = ">=1.4.7,<2"
r-jsonlite = ">=2.0.0,<3"
r-leaflet = ">=2.2.3,<3"
r-lubridate = ">=1.9.4,<2"
r-plotrix = ">=3.8_4,<4"
r-purrr = ">=1.2.0,<2"
r-sciplot = ">=1.2_0,<2"
r-shiny = ">=1.11.1,<2"
r-tidyverse = ">=2.0.0,<3"
r-reprex = ">=2.1.1,<3"
libcurl = ">=8.17.0,<9"
