[workspace]
authors = ["Francesco Frassinelli <francesco.frassinelli@nina.no>"]
channels = ["conda-forge"]
name = "coat-shiny"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r = ">=4.5,<4.6"
